# Generated by Django 5.0.6 on 2024-05-09 18:23

import utils.model_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='description',
            field=models.CharField(help_text='Descricao do Site com no máximo 255 caracteres.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', help_text='Icone a ser exibido na abado navegador.', upload_to='assets/favicon/%Y/%m/', validators=[utils.model_validator.validate_png]),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='title',
            field=models.CharField(help_text='Titulo do Site com no máximo 65 caracteres.', max_length=65),
        ),
    ]
