# Generated by Django 5.0.6 on 2024-05-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Este campo precisara estar marcado para a pagina seja exibida.'),
        ),
    ]
